# Generated by Django 5.0.3 on 2024-03-20 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("students", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Branch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch", models.CharField(max_length=50)),
                ("branch_code", models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="CourseList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credit", models.IntegerField()),
                ("course_id", models.CharField(max_length=10)),
                ("course_name", models.CharField(max_length=100)),
                (
                    "cdcs",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FY", "First Year"),
                            ("SY1", "Second Year Sem 1"),
                            ("SY2", "Second Year Sem 1"),
                            ("TY1", "Third Year Sem 1"),
                            ("TY2", "Third Year Sem 2"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "electives",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("DEL", "Department Elective"),
                            ("OPEL", "Open Elective"),
                            ("HEL", "Humanities Elective"),
                        ],
                        max_length=4,
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.branch",
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Courses",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("marks", models.IntegerField()),
                ("grade", models.CharField(max_length=2, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.courselist",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.students",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Courses",
            },
        ),
        migrations.AddField(
            model_name="branch",
            name="dept",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="professors.department"
            ),
        ),
        migrations.CreateModel(
            name="Professors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "designation",
                    models.CharField(
                        choices=[
                            ("HOD", "Head of Departemnt"),
                            ("PRO", "Professor"),
                            ("AIP", "Assistant Professor"),
                            ("AOP", "Associate Professor"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "courses",
                    models.ManyToManyField(
                        related_name="prof", to="professors.courselist"
                    ),
                ),
                (
                    "dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="professors.department",
                    ),
                ),
                (
                    "prof",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Professors",
            },
        ),
    ]
