# Generated by Django 5.0.3 on 2024-03-20 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courselist",
            name="branch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="professors.branch",
            ),
        ),
    ]
