# Generated by Django 5.0.3 on 2024-03-17 16:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("professors", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="content",
            old_name="attachemnts",
            new_name="attachments",
        ),
    ]
