# Generated by Django 5.0.3 on 2024-03-21 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("professors", "0007_alter_courselist_cdcs"),
    ]

    operations = [
        migrations.AddField(
            model_name="courses",
            name="date_added",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
