# Generated by Django 5.0.3 on 2024-03-22 12:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("professors", "0008_courses_date_added"),
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="courses",
            unique_together={("student", "course")},
        ),
    ]
